### ISSUE TITLE
Possible to transmit IR code without first receiving IR code?

### ISSUE THREAD

**Issue by BenJamesAndo** [vincebusam/flirc_retransmit#2]
Hello. Thanks for making this.
I've got it running on my Raspberry Pi 4. It seems this program only retransmits an IR signal once it's received a signal from a remote? Is it possible to invoke it sending an IR signal simply by running a command in the terminal?

My use case is I want to be able to turn on a super old TV that doesn't support HDMI CEC. If I could get the Raspberry Pi to turn it on all locally without the need for an additional WiFi smart IR blaster that'd be great.

**Comment by vincecitizennet** [comment]
`flirc_util sendir` will do that.

**Comment by BenJamesAndo** [comment]
Thanks for the info.
I managed to install `flirc_util sendir` with `curl apt.flirc.tv/install.sh | sudo bash`
